name: Docker Build and Push

on:
  workflow_call:
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
    inputs:
      platforms:
        required: true
        type: string
      tags:
        required: true
        type: string
      docker_image:
        required: true
        type: string
      docker_file:
        required: false
        type: string
        default: Dockerfile.yubikey
      docker_build_args:
        required: false
        type: string
      runs_on:
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  build_upload_docker:
    name: Build & Upload Docker Images
    runs-on: ${{ inputs.runs_on }}
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: Setup Go
        uses: actions/setup-go
        with:
          go-version: 'stable'
          check-latest: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action
      - name: Login to Docker Hub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install cosign
        uses: sigstore/cosign-installer
        with:
          cosign-release: 'v2.2.4'
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action
        with:
          context: .
          file: ${{ inputs.docker_file }}
          push: true
          tags: ${{ inputs.tags }}
          platforms: ${{ inputs.platforms }}
          build-args: ${{ inputs.docker_build_args }}
      - name: Cosign
        id: cosign
        run: |
          cosign sign -r ${{ inputs.docker_image }}@${{ steps.build-and-push.outputs.digest }} --yes