name: Docker Build and Push

on:
  push:

jobs:
  build_upload_docker:
    name: Build & Upload Docker Images
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout
      - name: Setup Go
        uses: actions/setup-go
        with:
          go-version: 'stable'
          check-latest: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action
      - name: Login to Docker Hub
        uses: docker/login-action
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install cosign
        uses: sigstore/cosign-installer
        with:
          cosign-release: 'v2.2.4'
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action
        with:
          context: .
          file: Dockerfile.yubikey
          push: true
          tags: maxwelldps/step-ca:yubikey,maxwelldps/step-ca:${{ github.sha }}-yubikey
          platforms: linux/amd64,linux/386,linux/arm,linux/arm64

      - name: Cosign
        id: cosign
        run: |
          cosign sign -r maxwelldps/step-ca@${{ steps.build-and-push.outputs.digest }} --yes
