name: Create Release & Upload Assets

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  ci:
    uses: maxwelldps/certificates/.github/workflows/ci.yml@master
    secrets: inherit

  build_upload_docker:
    name: Build & Upload Docker Images
    needs: create_release
    permissions:
      id-token: write
      contents: write
    uses: .github/workflows/docker-buildx-push.yml@main
    with:
      platforms: linux/amd64,linux/386,linux/arm,linux/arm64
      tags: ${{ needs.create_release.outputs.docker_tags }}
      docker_image: maxwelldps/step-ca
      docker_file: docker/Dockerfile
    secrets: inherit

